### ISSUE TITLE
Failing with --quality-gate-status on sonarcloud.io

### ISSUE THREAD

**Issue by pragnesh-is** [soprasteria/sonar-report#163]
No proxy configuration detected
sonarqube version: 8.0.0
"/usr/local/lib/node_modules/sonar-report/summary.txt.ejs":45
    ; __append(escapeFn( qualityGateStatus.projectStatus.period.date ))
                                                                ^

TypeError: /usr/local/lib/node_modules/sonar-report/summary.txt.ejs:14
    12| <%_ } _%>
    13| <%_ if (qualityGateStatus) { _%>
 >> 14| Quality gate status: <%= qualityGateStatus.projectStatus.status %> on <%= qualityGateStatus.projectStatus.period.date %> (<%= qualityGateStatus.projectStatus.period.parameter %>)<
    15| 
    16| <%_ for (const condition of qualityGateStatus.projectStatus.conditions) { _%>
    17| Metric: <%= condition.metricKey %></td>

Cannot read properties of undefined (reading 'date')
    at eval ("/usr/local/lib/node_modules/sonar-report/summary.txt.ejs":45:65)
    at summary.txt (/usr/local/lib/node_modules/sonar-report/node_modules/ejs/lib/ejs.js:703:17)
    at /usr/local/lib/node_modules/sonar-report/node_modules/ejs/lib/ejs.js:260:40
    at new Promise (<anonymous>)
    at tryHandleCache (/usr/local/lib/node_modules/sonar-report/node_modules/ejs/lib/ejs.js:258:14)
    at Object.exports.renderFile (/usr/local/lib/node_modules/sonar-report/node_modules/ejs/lib/ejs.js:491:10)
    at generateReport (file:///usr/local/lib/node_modules/sonar-report/index.js:464:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  path: '/usr/local/lib/node_modules/sonar-report/summary.txt.ejs'
}

**Comment by thecampagnards** [comment]
Released in https://github.com/soprasteria/sonar-report/releases/tag/3.0.9
