### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by sherknil** [soprasteria/sonar-report#269]
Getting below error while generating sonar report

**sonarqube version: 10.2.1**

H:\Agents\Agent002\_work\_tool\node\10.14.2\x64\node_modules\sonar-report\cli.js:2
import { buildCommand, generateReport } from "./index.js";
       ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)

**Comment by cwilli-it** [comment]
upgrade node.js and try again?
