### ISSUE TITLE
SonarBaseUrl Issue

### ISSUE THREAD

**Issue by chanduaki** [soprasteria/sonar-report#49]
# summary

Getting errors
```
  sonarBaseURL: argv.sonarurl.replace("/\/$/", ""),
                              ^

TypeError: Cannot read property 'replace' of undefined
    at Object.<anonymous> (/home/ib-developer/chandu/sonar-report/index.js:82:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    
 ```

**Comment by ptrovatelli** [comment]
hello @chanduaki 

can you post the exact command you ran and the full output? it seems that the `--sonarurl` argument is missing

**Comment by chanduaki** [comment]
Installation Successful
```
~/chandu/content_management_portal$ npm install -g sonar-report
/home/ib-developer/.nvm/versions/node/v14.4.0/bin/sonar-report -> /home/ib-developer/.nvm/versions/node/v14.4.0/lib/node_modules/sonar-report/index.js

> ejs@2.7.4 postinstall /home/chandu/content_management_portal/sonar-report/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

+ sonar-report@1.2.0
added 36 packages from 66 contributors in 3.714s
```

Generated Report using the below command
```
sonar-report --project=content_management_portal --application=content_management_portal --release=v1.0.0 --sonarurl=http://localhost:9000/dashboard?id=content_management_portal --sonarcomponent=myapp:1.0.0 --sinceleakperiod=true > /tmp/sonar-report.html
```
Response
```
</span></div></div><script>window.baseUrl = '';
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/home/chandu/sonar-report/index.js:137:21)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```


```
~/chandu/content_management_portal$ sonar-report
/home/chandu/node_modules/sync-rpc/lib/index.js:167
    throw error;
    ^

Error: The protocol "" is not supported, cannot load "undefined/api/rules/search?activation=true&ps=500&p=1&types=VULNERABILITY,SECURITY_HOTSPOT"
    at extractValue (/home/chandu/node_modules/sync-rpc/lib/index.js:165:19)
    at /home/ib-developer/chandu/node_modules/sync-rpc/lib/index.js:175:12
    at request (/home/chandu/node_modules/sync-request/lib/index.js:28:15)
    at Object.<anonymous> (/home/chandu/sonar-report/index.js:147:17)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: undefined
}
```

**Comment by ptrovatelli** [comment]
@chanduaki there is an url now but still it doesn't seem correct; the --sonar-url should just be the host as in the example:  `--sonarurl="https://sonarcloud.io" ` because the API paths are built from that

**Comment by chanduaki** [comment]
# Summary

Zero vulnerabilities are found when i had executed the below command, can you please help me out of this

Command used
```

sonar-report   \
--sonarurl="http://localhost:9000/"   \
--sonarcomponent="testing"   \
--project="TESTING"   \
--application="TESTING"   \
--release="1.0.0"   \
--sinceleakperiod="false"  \
--sonartoken="5c05a9c984e1af643d3a5c96ffaffbff6ca4cd88"   \
--allbugs="true" --noSecurityHotspot="true" > /tmp/sonar-report_sonar-report.html

```

This command is taken from https://github.com/soprasteria/sonar-report/issues/45 
can you please provide the exact command for getting the sonar-report

**Comment by ptrovatelli** [comment]
hello @chanduaki . are you sure of your component name? are there findings out of the security hotspots? are there findings on master branch?

**Comment by chanduaki** [comment]
Hi @ptrovatelli 

>  are you sure of your component name?
```
I had give an component name as same as application name , did not find that name. can you please share at where i find the component .
It is python Django based project
```
> are there findings out of the security hotspots? 
```
No ,  as mentioned in the above query 
> Zero vulnerabilities are found
```
are there findings on master branch?
```
No
```

**Comment by ptrovatelli** [comment]
The component needs to be the same as in sonarqube. If you're using multibranch analysis there s an issue which makes the vulnerabilities accessible from master only when using the API. Try to add vulnerability in master see if it fixes it.

**Comment by ptrovatelli** [comment]
hello @chanduaki . did you solve the problem?

**Comment by chanduaki** [comment]
Yes @ptrovatelli 

Its Resolved for me
