### ISSUE TITLE
Questions on generating sonar-report

### ISSUE THREAD

**Issue by chanduaki** [soprasteria/sonar-report#53]
# Scenario

while generating the `sonar-report` , facing the below issues
Can you tell the further steps in resolving this

```

✦4 ❯ sudo npm install -g sonar-report
/usr/local/bin/sonar-report -> /usr/local/lib/node_modules/sonar-report/index.js
+ sonar-report@2.0.0
updated 1 package in 1.077s

✦4 ❯ sonar-report
(node:128122) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at /usr/local/lib/node_modules/sonar-report/index.js:99:33
    at Object.<anonymous> (/usr/local/lib/node_modules/sonar-report/index.js:290:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
(node:128122) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:128122) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

✦4 ❯ sonar-report --project="Content Management Portal" --application="Content Management Portal" --release="1.0.0" --sonarurl="http://localhost:9000" --sonarcomponent="content-management-portal" > sonar-report
No proxy configuration detected
Error while while getting rules :  - Response code 401 (Unauthorized) - 401 - Unauthorized - 
```

**Comment by Homopatrol** [comment]
@chanduaki I believe you need to supply a either `--sonartoken` or  a `--sonarusername`  & `--sonarpassword`.

To generate a token:
Log on to Sonarqube, (visit http://localhost:9000) , then:

    Click on Administration > Security > Users. Underneath 'Tokens' click 'update token'.

Create a name for the token and save this to be used.

**Comment by ptrovatelli** [comment]
lack of authentication to sonar (not an issue)
